from __future__ import annotations

import os
import re
from html import unescape


ARABIZE_UI_ENABLED = os.getenv("HOBEHUB_ARABIZE_UI", "1").strip().lower() not in {
    "0",
    "false",
    "no",
    "off",
}


TERM_TRANSLATIONS = {
    "RADIUS_API_WRITES_ENABLED": "تفعيل الكتابة على خدمة المصادقة",
    "RADIUS_API_MASTER_KEY": "المفتاح الرئيسي لواجهة المصادقة",
    "RADIUS_API_PASSWORD": "كلمة مرور واجهة المصادقة",
    "RADIUS_API_USERNAME": "اسم مستخدم واجهة المصادقة",
    "RADIUS_API_BASE_URL": "رابط واجهة المصادقة",
    "RADIUS_API_READY": "جاهزية واجهة المصادقة",
    "MIKROTIK_HOTSPOT_URL": "رابط بوابة مايكروتك",
    "RADIUS_MODE": "وضع خدمة المصادقة",
    "DATABASE_URL": "رابط قاعدة البيانات",
    "FLASK_SECRET_KEY": "المفتاح السري للتطبيق",
    "HOBEHUB_LOCAL_DEMO_SEED": "تعبئة البيانات التجريبية",
    "HOBEHUB_LOCAL_DEMO": "الوضع المحلي التجريبي",
    "HOBEHUB_LOCAL_DB_PATH": "مسار قاعدة البيانات المحلية",
    "System Administrator": "مدير النظام",
    "Administrator": "مدير النظام",
    "System": "النظام",
    "app_ad2": "واجهة الربط",
    "app_ad": "واجهة الربط",
    "RADIUS API": "واجهة ربط المصادقة",
    "RADIUS": "نظام المصادقة",
    "MikroTik Hotspot": "بوابة مايكروتك",
    "MikroTik": "مايكروتك",
    "Hotspot": "بوابة الاتصال",
    "Hobe Hub": "هوب هب",
    "HobeHub": "هوب هب",
    "API": "واجهة الربط",
    "api": "واجهة الربط",
    "CSV": "ملف جدولي",
    "csv": "ملف جدولي",
    "XLSX": "ملف إكسل",
    "xlsx": "ملف إكسل",
    "XLSM": "ملف إكسل",
    "xlsm": "ملف إكسل",
    "Excel": "إكسل",
    "JSON": "بيانات منظمة",
    "json": "بيانات منظمة",
    "HTTP": "بروتوكول الويب",
    "http": "بروتوكول الويب",
    "POST": "إرسال",
    "post": "إرسال",
    "GET": "قراءة",
    "get": "قراءة",
    "URL": "الرابط",
    "url": "الرابط",
    "ID": "المعرّف",
    "id": "المعرّف",
    "IP": "عنوان الشبكة",
    "ip": "عنوان الشبكة",
    "MAC": "عنوان الجهاز",
    "mac": "عنوان الجهاز",
    "MD5": "تشفير قديم",
    "MD": "تشفير قديم",
    "SMS": "رسالة نصية",
    "QR": "رمز الاستجابة",
    "VPS": "خادم خاص",
    "VPN": "شبكة خاصة",
    "WireGuard": "شبكة خاصة آمنة",
    "PostgreSQL": "قاعدة الإنتاج",
    "SQLite": "قاعدة محلية",
    "Redis": "مخزن مؤقت",
    "Render": "منصة الاستضافة",
    "Flask": "التطبيق",
    "Python": "بايثون",
    "Jinja": "قوالب الصفحات",
    "HTML": "صفحة ويب",
    "CSS": "تنسيق الصفحة",
    "JavaScript": "جافاسكربت",
    "JS": "جافاسكربت",
    "Client-side": "من جهة المتصفح",
    "client-side": "من جهة المتصفح",
    "License Key": "مفتاح الترخيص",
    "License": "الترخيص",
    "Endpoint": "نقطة الربط",
    "Endpoints": "نقاط الربط",
    "endpoint": "نقطة الربط",
    "endpoints": "نقاط الربط",
    "health_check": "فحص الاتصال",
    "get_app_version": "قراءة إصدار الخدمة",
    "get_my_permissions": "قراءة صلاحياتي",
    "get_my_balance": "قراءة رصيدي",
    "get_server_status": "قراءة حالة الخادم",
    "get_online_users": "قراءة المتصلين الآن",
    "quick_stats": "إحصائيات سريعة",
    "get_dashboard_metrics": "قراءة مؤشرات اللوحة",
    "get_profiles_for_user": "قراءة باقات المشترك",
    "get_profiles": "قراءة الباقات",
    "search_users": "بحث المشتركين",
    "full_suite": "الفحص الكامل",
    "search_demo": "تجربة البحث",
    "server_status": "حالة الخادم",
    "online_users": "المتصلون الآن",
    "auth": "التوثيق",
    "env": "بيئة التشغيل",
    "Ping": "فحص الاتصال",
    "ping": "فحص الاتصال",
    "Dashboard": "لوحة التحكم",
    "Admin": "الإدارة",
    "admin": "الإدارة",
    "Login": "تسجيل الدخول",
    "login": "تسجيل الدخول",
    "Logout": "تسجيل الخروج",
    "logout": "تسجيل الخروج",
    "Username": "اسم المستخدم",
    "username": "اسم المستخدم",
    "Password": "كلمة المرور",
    "password": "كلمة المرور",
    "pass": "كلمة المرور",
    "Profile": "باقة السرعة",
    "Profiles": "باقات السرعة",
    "profile": "باقة السرعة",
    "profiles": "باقات السرعة",
    "User": "مشترك",
    "Users": "المشتركون",
    "user": "مشترك",
    "users": "المشتركون",
    "Card": "بطاقة",
    "Cards": "البطاقات",
    "card": "بطاقة",
    "cards": "البطاقات",
    "Manager": "مدير",
    "Managers": "المديرون",
    "manager": "مدير",
    "managers": "المديرون",
    "Permission": "صلاحية",
    "Permissions": "الصلاحيات",
    "permission": "صلاحية",
    "permissions": "الصلاحيات",
    "Status": "الحالة",
    "status": "الحالة",
    "Online": "متصل الآن",
    "online": "متصل الآن",
    "Offline": "غير متصل",
    "offline": "غير متصل",
    "Active": "نشط",
    "active": "نشط",
    "Inactive": "معطّل",
    "inactive": "معطّل",
    "Pending": "قيد الانتظار",
    "pending": "قيد الانتظار",
    "Approved": "موافق عليه",
    "approved": "موافق عليه",
    "Rejected": "مرفوض",
    "rejected": "مرفوض",
    "Done": "منجز",
    "done": "منجز",
    "Success": "نجاح",
    "success": "نجاح",
    "Failed": "فشل",
    "failed": "فشل",
    "Error": "خطأ",
    "error": "خطأ",
    "Warning": "تنبيه",
    "warning": "تنبيه",
    "Info": "معلومة",
    "info": "معلومة",
    "OK": "تم",
    "ok": "تم",
    "True": "نعم",
    "False": "لا",
    "true": "نعم",
    "false": "لا",
    "None": "لا يوجد",
    "Null": "لا يوجد",
    "null": "لا يوجد",
    "Default": "افتراضي",
    "default": "افتراضي",
    "Manual": "يدوي",
    "manual": "يدوي",
    "Auto": "تلقائي",
    "auto": "تلقائي",
    "Live": "مباشر",
    "live": "مباشر",
    "Local": "محلي",
    "local": "محلي",
    "Demo": "تجريبي",
    "demo": "تجريبي",
    "Mode": "الوضع",
    "mode": "الوضع",
    "Cache": "الذاكرة المؤقتة",
    "cache": "الذاكرة المؤقتة",
    "Search": "بحث",
    "search": "بحث",
    "Filter": "تصفية",
    "filter": "تصفية",
    "Export": "تصدير",
    "export": "تصدير",
    "Import": "استيراد",
    "import": "استيراد",
    "Backup": "نسخة احتياطية",
    "backup": "نسخة احتياطية",
    "Archive": "أرشيف",
    "archive": "أرشيف",
    "Settings": "الإعدادات",
    "settings": "الإعدادات",
    "File": "ملف",
    "file": "ملف",
    "Files": "ملفات",
    "files": "ملفات",
    "Upload": "رفع",
    "upload": "رفع",
    "Download": "تنزيل",
    "download": "تنزيل",
    "MB": "ميجابايت",
    "GB": "جيجابايت",
    "KB": "كيلوبايت",
    "Mbps": "ميجابت/ث",
    "ms": "مللي ثانية",
    "B": "بايت",
    "ILS": "شيكل",
    "DELETE": "حذف",
    "DEMO": "تجريبي",
    "whitelist": "القائمة المسموحة",
    "connection_issue": "مشكلة اتصال",
    "change_mac": "تغيير عنوان الجهاز",
    "reset_password": "تغيير كلمة المرور",
    "open_blocked_site": "فتح موقع محظور",
    "extra_quota": "حصة إضافية",
    "connection": "الاتصال",
    "issue": "مشكلة",
    "request": "طلب",
    "change": "تغيير",
    "reset": "إعادة ضبط",
    "open": "فتح",
    "blocked": "محظور",
    "site": "موقع",
    "extra": "إضافي",
    "quota": "حصة",
    "speed": "السرعة",
    "upgrade": "رفع",
    "create": "إنشاء",
    "add": "إضافة",
    "edit": "تعديل",
    "delete": "حذف",
    "remove": "إزالة",
    "server": "الخادم",
    "version": "الإصدار",
    "balance": "الرصيد",
    "my": "الخاصة بي",
    "app": "التطبيق",
    "ad": "الإدارة",
    "modal": "نافذة",
    "client": "العميل",
    "side": "الجانب",
    "unknown": "غير معروف",
    "QA": "ضمان الجودة",
    "We": "نحن",
    "Will": "سننجز",
    "fatema": "فاطمة",
    "alaa": "علاء",
    "USED": "مستخدمة",
    "used": "مستخدمة",
    "profile_id": "معرّف الباقة",
    "profile_1h": "باقة ساعة",
    "ten_minutes": "عشر دقائق",
    "FontAwesome": "أيقونة جاهزة",
    "fa-clock": "أيقونة ساعة",
    "priority": "الأولوية",
    "sat": "السبت",
    "sun": "الأحد",
    "mon": "الإثنين",
    "tue": "الثلاثاء",
    "wed": "الأربعاء",
    "thu": "الخميس",
    "NAS": "نقطة الشبكة",
    "nas": "نقطة الشبكة",
    "radacct": "سجل الجلسات",
    "owner_id": "معرّف المالك",
    "man_id": "معرّف المدير",
    "CoA": "أمر تحكم",
    "Disconnect": "قطع الاتصال",
    "disconnect": "قطع الاتصال",
    "Meta": "بيانات إضافية",
    "refresh": "تحديث",
    "Base": "الرابط الأساسي",
    "base": "الرابط الأساسي",
    "https": "رابط آمن",
    "host": "الخادم",
    "sub-admin": "مدير فرعي",
    "DB": "قاعدة البيانات",
    "ahmad_net": "شبكة أحمد",
    "ahmad": "أحمد",
    "Premium": "مميز",
    "AA": "مثال",
    "BB": "مثال",
    "CC": "مثال",
    "DD": "مثال",
    "EE": "مثال",
    "FF": "مثال",
    "Back-End": "تطوير خلفي",
    "Front-End": "تطوير واجهات",
    "Full-Stack": "تطوير شامل",
    "Web": "ويب",
    "web": "ويب",
    "developer": "مطوّر",
    "Designer": "مصمم",
    "Dersigner": "مصمم",
    "Digital": "رقمي",
    "Trends": "اتجاهات",
    "Up": "أب",
    "Lancer": "لانسر",
    "ios": "تطبيقات آيفون",
    "team": "فريق",
    "lead": "قائد",
    "TenTime": "تن تايم",
    "Tradeep": "تريدب",
    "Zagency": "زد أجينسي",
    "TS": "دعم تقني",
    "MSI": "إم إس آي",
    "UI": "واجهة المستخدم",
    "UX": "تجربة المستخدم",
    "audit": "التدقيق",
    "log": "السجل",
    "logs": "السجلات",
    "SQL": "نسخة قاعدة البيانات",
    "sql": "نسخة قاعدة البيانات",
    "INSERT": "أمر إدخال",
    "insert": "أمر إدخال",
    "policy": "سياسة",
    "policies": "سياسات",
    "group": "مجموعة",
    "groups": "مجموعات",
    "member": "عضو",
    "members": "أعضاء",
    "beneficiary": "مستفيد",
    "beneficiaries": "المستفيدون",
    "account": "حساب",
    "accounts": "حسابات",
    "category": "فئة",
    "categories": "فئات",
    "inventory": "المخزون",
    "usage": "الاستخدام",
    "radius": "نظام المصادقة",
    "radius_api": "واجهة المصادقة",
    "radius_settings": "إعدادات المصادقة",
    "portal": "البوابة",
    "beneficiary_portal_account": "حساب بوابة المشترك",
    "manual_access_cards": "بطاقات الدخول اليدوية",
    "card_quota_policies": "سياسات حصص البطاقات",
    "operator": "المشغّل",
    "system": "النظام",
    "manual": "يدوي",
    "minutes": "دقائق",
    "minute": "دقيقة",
    "hour": "ساعة",
    "hours": "ساعات",
    "day": "يوم",
    "one_hour": "ساعة واحدة",
    "two_hours": "ساعتان",
    "three_hours": "ثلاث ساعات",
    "four_hours": "أربع ساعات",
    "six_hours": "ست ساعات",
    "half_hour": "نصف ساعة",
    "tawjihi": "توجيهي",
    "university": "جامعي",
    "freelancer": "عمل حر",
    "all_beneficiaries": "كل المستفيدين",
    "portal_accounts": "حسابات البوابة",
    "admin_accounts": "حسابات الإدارة",
    "cards_inventory": "مخزون البطاقات",
    "card_categories": "فئات البطاقات",
    "quota_policies": "سياسات الحصص",
    "quota_groups": "مجموعات السياسات",
    "group_members": "أعضاء المجموعات",
    "usage_logs": "سجل الاستخدام",
    "audit_logs": "سجل العمليات",
    "beneficiaries_backup": "نسخة المستفيدين",
    "convert_access_mode": "تغيير طريقة الوصول",
    "convert_access": "تغيير طريقة الوصول",
    "portal_move_in": "إضافة إلى حسابات البوابة",
    "set_tier": "تغيير صلاحية البطاقات",
    "set_verification": "تعديل التوثيق",
    "portal_reset": "تصفير حساب البوابة",
    "portal_view_credentials": "عرض بيانات دخول البوابة",
    "portal_set_credentials": "تعديل بيانات دخول البوابة",
    "portal_delete": "حذف حساب بوابة",
    "manage_portal_account": "إدارة حساب البوابة",
    "quick_edit_full": "تعديل سريع شامل",
    "type_change": "تغيير نوع المشترك",
    "admin_issue_card": "إصدار بطاقة",
    "admin_issue_card_manual": "إصدار بطاقة يدويًا",
    "issue_card": "إصدار بطاقة",
    "import_manual_cards": "استيراد بطاقات يدوية",
    "user_type_card_rules_save": "تحديث قواعد البطاقات حسب النوع",
    "edit_quota_policy": "تعديل سياسة حصص البطاقات",
    "delete_quota_policy": "حذف سياسة حصص البطاقات",
    "delete_card_category": "حذف فئة بطاقات",
    "quota_group_create": "إنشاء مجموعة سياسات",
    "quota_group_member_add": "إضافة عضو لمجموعة سياسات",
    "user_message_add": "إضافة ملاحظة للمشترك",
    "user_message_delete": "حذف ملاحظة من المشترك",
    "attachment_upload": "رفع مرفق",
    "attachment_delete": "حذف مرفق",
    "api_test_run": "فحص واجهة الربط",
    "test_advradius_app_api_failed": "فشل فحص واجهة الربط",
    "add_ajax": "إضافة سريعة",
    "sync_radius": "مزامنة مع نظام المصادقة",
    "يوزر إنترنت دائم": "حساب إنترنت دائم",
    "يوزر": "حساب",
}


_TERM_REPLACERS = [
    (
        re.compile(r"(?<![A-Za-z0-9_])" + re.escape(source) + r"(?![A-Za-z0-9_])"),
        target,
    )
    for source, target in sorted(TERM_TRANSLATIONS.items(), key=lambda item: len(item[0]), reverse=True)
]

_EMBEDDED_REPLACERS = [
    (re.compile(r"DEMO(?=\d)", re.I), "تجريبي"),
    (re.compile(r"USED(?=\d)", re.I), "مستخدمة"),
    (re.compile(r"TS(?=\d)", re.I), "دعم تقني"),
    (re.compile(r"\buser-(?=\d)", re.I), "مشترك-"),
    (re.compile(r"\bpass(?=\d)", re.I), "كلمة-"),
]
_LATIN_TOKEN_RE = re.compile(r"[A-Za-z]{2,}(?:[_-][A-Za-z0-9]+)*")

_TAG_RE = re.compile(r"(<[^>]+>)", re.S)
_TAG_NAME_RE = re.compile(r"^<\s*/?\s*([A-Za-z0-9:-]+)")
_TRANSLATABLE_ATTR_RE = re.compile(
    r'\b(placeholder|title|aria-label|alt|data-label)\s*=\s*(?:"([^"]*)"|\'([^\']*)\')',
    re.I,
)
_SKIP_TEXT_TAGS = {"script", "style", "textarea"}


def arabize_text(value) -> str:
    if value is None:
        return ""
    text = str(value)
    if not text:
        return ""
    text = unescape(text)
    for pattern, replacement in _TERM_REPLACERS:
        text = pattern.sub(replacement, text)
    for pattern, replacement in _EMBEDDED_REPLACERS:
        text = pattern.sub(replacement, text)
    return text


def arabize_audit_text(value) -> str:
    text = arabize_text(value)
    return _LATIN_TOKEN_RE.sub("رمز داخلي", text)


def arabize_html_fragment(html: str) -> str:
    if not ARABIZE_UI_ENABLED or not html:
        return html
    parts = _TAG_RE.split(html)
    stack: list[str] = []
    out: list[str] = []
    for part in parts:
        if not part:
            continue
        if part.startswith("<") and part.endswith(">"):
            tag = part
            match = _TAG_NAME_RE.match(tag)
            if match:
                name = match.group(1).lower()
                is_close = tag.startswith("</")
                is_self_close = tag.rstrip().endswith("/>")
                if not is_close and not is_self_close and name in _SKIP_TEXT_TAGS:
                    stack.append(name)
                elif is_close and stack and stack[-1] == name:
                    stack.pop()
            if not stack:
                tag = _TRANSLATABLE_ATTR_RE.sub(
                    lambda m: (
                        f'{m.group(1)}="{arabize_text(m.group(2))}"'
                        if m.group(2) is not None
                        else f"{m.group(1)}='{arabize_text(m.group(3))}'"
                    ),
                    tag,
                )
            out.append(tag)
        elif stack:
            out.append(part)
        else:
            out.append(arabize_text(part))
    return "".join(out)
