"""Compatibility loader for the split Hobe Hub legacy application."""
from __future__ import annotations

from pathlib import Path

_LEGACY_PARTS_DIR, _LEGACY_TEMPLATES_DIR = Path(__file__).with_name("legacy_parts"), Path(__file__).with_name("legacy_templates")
_LEGACY_PARTS = [
    '00_bootstrap_config.py',
    '01_sqlite_compat.py',
    '02_permissions_options.py',
    '03_admin_base_template.py',
    '04_security_auth.py',
    '05_database_connection.py',
    '06_import_task_state.py',
    '07_import_processing_01.py',
    '07_import_processing_02.py',
    '08_query_helpers.py',
    '09_formatting_signup_helpers_01.py',
    '09_formatting_signup_helpers_02.py',
    '10_manual_cards_services_01.py',
    '10_manual_cards_services_02.py',
    '11_usage_audit_permissions.py',
    '12_csrf_context_hooks.py',
    '13_access_decorators_rendering.py',
    '14_user_base_template.py',
    '15_sqlite_seed_data.py',
    '16_sqlite_schema_01_people_usage.py',
    '16_sqlite_schema_02_radius.py',
    '16_sqlite_schema_03_portal_cards.py',
    '16_sqlite_schema_04_seed_defaults.py',
    '16_sqlite_schema_04a_card_management.py',
    '16_sqlite_schema_05_entrypoint.py',
    '17_postgres_schema_setup_01_people_accounts.py',
    '17_postgres_schema_setup_02_usage_timer.py',
    '17_postgres_schema_setup_03_radius_internet.py',
    '17_postgres_schema_setup_04_seed_defaults.py',
    '17_postgres_schema_setup_04a_card_management.py',
    '17_postgres_schema_setup_05_entrypoint.py',
    '17_postgres_schema_setup_06_runner.py',
    '18_dashboard_services_01.py',
    '18_dashboard_services_02.py',
    '20_beneficiary_table_helpers_01.py',
    '20_beneficiary_table_helpers_02.py',
    '21_beneficiaries_page_01_context.py',
    '21_beneficiaries_page_02_content.py',
    '21_beneficiaries_page_03_route.py',
    '22_beneficiary_crud_routes_01.py',
    '22_beneficiary_crud_routes_02.py',
    '22_beneficiary_crud_routes_03.py',
    '23_import_routes_01.py',
    '23_import_routes_02.py',
    '24_export_backup_routes_01.py',
    '24_export_backup_routes_02.py',
    '25_usage_logs_routes_01.py',
    '25_usage_logs_routes_02.py',
    '26_usage_archive_routes.py',
    '27_account_routes_01.py',
    '27_account_routes_02.py',
    '28_power_timer_routes.py',
    '29_audit_log_route.py',
    '30_template_overrides_01.py',
    '30_template_overrides_02.py',
    '31_beneficiary_patch_routes_01.py',
    '31_beneficiary_patch_routes_02.py',
    '32_admin_control_routes_01.py',
    '32_admin_control_routes_02.py',
    '32_admin_control_routes_03.py',
    '33_internet_request_labels.py',
    '34_radius_internet_services_01.py',
    '34_radius_internet_services_02.py',
    '34_radius_internet_services_03.py',
    '34_radius_internet_services_04.py',
    '35_portal_account_services_01.py',
    '35_portal_account_services_02.py',
    '36_user_internet_routes_01.py',
    '36_user_internet_routes_02.py',
    '37_admin_alias_portal_routes.py',
    '38_admin_internet_request_routes_01.py',
    '38_admin_internet_request_routes_02.py',
    '38_admin_internet_request_routes_03.py',
    '39_radius_admin_routes_01.py',
    '39_radius_admin_routes_02.py',
    '40_user_activation_patch_routes_01.py',
    '40_user_activation_patch_routes_02.py',
    '40_user_activation_patch_routes_03.py',
    '41_portal_redesign_foundation.py',
    '42_user_design_overrides_01.py',
    '42_user_design_overrides_02.py',
    '42_user_design_overrides_03.py',
    '42_user_design_overrides_04.py',
    '43_user_register_override_v2.py',
    '44_redesigned_portal_auth_01.py',
    '44_redesigned_portal_auth_02.py',
    '44_redesigned_portal_auth_03.py',
    '45_admin_cards_routes.py',
    '45a_admin_cards_v2_routes.py',
    '45b_admin_users_account_routes.py',
    '46a_user_cards_portal_routes.py',
    '46b_user_account_portal_routes.py',
    '47a_admin_api_test_routes.py',
    '47b_admin_radius_online_routes.py',
    '46_manual_cards_user_overrides.py',
    '47_clean_user_radius_overrides_01.py',
    '47_clean_user_radius_overrides_02.py',
    '47_clean_user_radius_overrides_03.py',
    '48_clean_admin_cards_overrides.py',
    '48a_admin_home_route.py',
    '48b_admin_beneficiaries_v2.py',
    '48c_admin_audit_log_v2.py',
    '48d_admin_internet_requests_v2.py',
    '48e_admin_usage_logs_v2.py',
    '48f_admin_accounts_v2.py',
    '48g_admin_radius_settings_v2.py',
    '48h_admin_import_export_v2.py',
    '48i_url_reorganization.py',
    '48j_radius_schema_extension.py',
    '48k_user_portal_redesign.py',
    '48l_default_cards_mode.py',
    '48m_cards_with_reason.py',
    '48n_cleanup_legacy.py',
    '48o_admin_forms_v2.py',
    '48p_user_cards_connect.py',
    '48q_admin_cards_inventory_controls.py',
    '48r_admin_misc_v2.py',
    '48s_card_uniqueness_guards.py',
    '48t_power_timer_viewer.py', '48u_fix_admin_aliases.py',
    '48v_force_new_admin_routes.py', '48w_quick_edit_api.py',
    '48x_portal_accounts_v2.py', '48y_phase1_portal_section.py',
    '48z_phase2_user_profile.py', '48aa_phase3_tiers.py',
    '48ab_phase4_attachments.py', '48ac_notifications_schema.py', '48ac_notifications_routes.py',
    '48ad_cards_policies_ajax.py', '48ae_quota_groups.py',
    '48af_cards_categories_ajax.py', '48ag_full_exports.py', '48ah_portal_import.py', '48ai_unified_login.py',
    '48aj_user_type_card_rules.py', '48ak_admin_cards_subscribers.py', '48al_system_cleanup_v2.py',
    '48am_sms_module.py', '48an_portal_documents.py', '48ao_subscriber_api_explorer.py', '48ap_radius_features.py',
    '48aq_master_admin_portal.py', '48ar_signup_phone_check.py',
    '49_main_entrypoint.py',
]
def _legacy_template_text(filename: str) -> str:
    return (_LEGACY_TEMPLATES_DIR / filename).read_text(encoding="utf-8")


def _load_legacy_part(filename: str, parts_dir=_LEGACY_PARTS_DIR) -> None:
    part_path = parts_dir / filename
    source = part_path.read_text(encoding="utf-8")
    exec(compile(source, str(part_path), "exec"), globals())


for _legacy_part in _LEGACY_PARTS:
    _load_legacy_part(_legacy_part)
del Path, _legacy_part, _load_legacy_part, _LEGACY_PARTS_DIR, _LEGACY_PARTS
