# Auto-split from app/legacy.py lines 245-374. Loaded by app.legacy.
PERMISSIONS = [
    "view",
    "add",
    "edit",
    "delete",
    "view_portal_accounts",
    "manage_portal_accounts",
    "view_user_accounts",
    "manage_user_accounts",
    "view_cards",
    "manage_card_inventory",
    "import_cards",
    "manage_card_categories",
    "manage_card_policies",
    "manage_quota_groups",
    "manage_card_requests",
    "import",
    "export",
    "backup",
    "usage_counter",
    "reset_weekly_usage",
    "manage_accounts",
    "view_audit_log",
    "view_archive",
    "archive_logs",
    "restore_archive",
    "export_archive",
    "delete_archive",
    "manage_bulk_ops",
    "manage_system_cleanup",
    "view_internet_requests",
    "submit_internet_requests",
    "manage_internet_requests",
    "approve_internet_requests",
    "execute_radius_actions",
    "view_radius_status",
    "disconnect_radius_user",
    "manage_radius_settings",
    "view_notifications",
    "manage_power_timer",
]

PERMISSION_LABELS = {
    "view": "عرض البيانات",
    "add": "إضافة مستفيد",
    "edit": "تعديل المستفيدين",
    "delete": "حذف المستفيدين",
    "view_portal_accounts": "عرض حسابات البوابة",
    "manage_portal_accounts": "إدارة حسابات البوابة",
    "view_user_accounts": "عرض حسابات الإنترنت",
    "manage_user_accounts": "إدارة حسابات الإنترنت",
    "view_cards": "عرض لوحة البطاقات",
    "manage_card_inventory": "إدارة مخزون البطاقات",
    "import_cards": "رفع بطاقات للمخزون",
    "manage_card_categories": "إدارة فئات البطاقات",
    "manage_card_policies": "إدارة سياسات البطاقات",
    "manage_quota_groups": "إدارة مجموعات السياسات",
    "manage_card_requests": "إدارة طلبات البطاقات",
    "import": "استيراد CSV",
    "export": "تصدير البيانات",
    "backup": "نسخة احتياطية",
    "usage_counter": "زر +1 للبطاقات",
    "reset_weekly_usage": "تجديد كل البطاقات",
    "manage_accounts": "إدارة المستخدمين والصلاحيات",
    "view_audit_log": "عرض سجل العمليات",
    "view_archive": "عرض أرشيف السجل",
    "archive_logs": "أرشفة سجل البطاقات",
    "restore_archive": "استرجاع من الأرشيف",
    "export_archive": "تصدير الأرشيف",
    "delete_archive": "تنظيف الأرشيف",
    "manage_bulk_ops": "التعديلات الجماعية",
    "manage_system_cleanup": "لوحة التنظيف والتصفير",
}

PERMISSION_LABELS.update({
    "view_internet_requests": "طلبات خدمات الإنترنت",
    "submit_internet_requests": "تقديم طلبات الإنترنت",
    "manage_internet_requests": "إدارة طلبات الإنترنت",
    "approve_internet_requests": "اعتماد طلبات الإنترنت",
    "execute_radius_actions": "تنفيذ إجراءات RADIUS",
    "view_radius_status": "عرض حالة RADIUS",
    "disconnect_radius_user": "فصل مستخدم RADIUS",
    "manage_radius_settings": "إدارة إعدادات RADIUS",
    "view_notifications": "عرض مركز الإشعارات",
    "manage_power_timer": "إدارة عداد تحويل الكهرباء",
})

PERMISSION_DESCRIPTIONS = {
    "view": "عرض صفحات المستفيدين والسجلات.",
    "add": "إضافة مستفيدين جدد إلى النظام.",
    "edit": "تعديل بيانات المستفيدين.",
    "delete": "حذف المستفيدين من السجل الحالي.",
    "view_portal_accounts": "الاطلاع على حسابات بوابة المشتركين وحالاتها.",
    "manage_portal_accounts": "إنشاء وتعديل حسابات بوابة المشتركين وتفعيلها أو تعطيلها.",
    "view_user_accounts": "عرض صفحات مشتركي حساب الإنترنت وقوائمهم.",
    "manage_user_accounts": "تنفيذ طلبات حسابات الإنترنت والتحويل بين البطاقات والحسابات.",
    "view_cards": "عرض لوحة البطاقات والملخصات العامة.",
    "manage_card_inventory": "استعراض وحذف وتنظيم مخزون البطاقات المتاحة والصادرة.",
    "import_cards": "رفع ملفات البطاقات إلى مخزون البطاقات.",
    "manage_card_categories": "إدارة فئات البطاقات وربطها بباقات RADIUS.",
    "manage_card_policies": "إدارة حدود وصلاحيات إصدار البطاقات.",
    "manage_quota_groups": "إنشاء مجموعات سياسات البطاقات وإدارة أعضائها.",
    "manage_card_requests": "متابعة طلبات البطاقات وتسليمها أو إلغاؤها.",
    "import": "استيراد بيانات CSV.",
    "export": "تصدير بيانات المستفيدين.",
    "backup": "نسخ احتياطي عام وعمليات حساسة.",
    "usage_counter": "إضافة بطاقات للمستفيدين.",
    "reset_weekly_usage": "تصفير العدادات الأسبوعية.",
    "manage_accounts": "إدارة المستخدمين والصلاحيات.",
    "view_audit_log": "فتح سجل العمليات الإدارية.",
    "view_archive": "عرض أرشيف سجل البطاقات.",
    "archive_logs": "أرشفة السجلات الحالية أو الجزئية.",
    "restore_archive": "استرجاع السجلات المؤرشفة إلى السجل الحالي.",
    "export_archive": "تصدير الأرشيف إلى Excel.",
    "delete_archive": "تنظيف الأرشيف نهائيًا.",
    "manage_bulk_ops": "تنفيذ تعديلات جماعية على مجموعات المستفيدين أو على الجميع.",
    "manage_system_cleanup": "تنفيذ مسح وتنظيف وتصفير متقدم على مجموعات أو على النظام.",
}

PERMISSION_DESCRIPTIONS.update({
    "view_internet_requests": "الاطلاع على طلبات خدمات الإنترنت وحالاتها.",
    "submit_internet_requests": "إنشاء طلبات خدمات إنترنت جديدة للمستفيدين.",
    "manage_internet_requests": "متابعة طلبات خدمات الإنترنت وإدارتها.",
    "approve_internet_requests": "الموافقة أو الرفض على طلبات خدمات الإنترنت.",
    "execute_radius_actions": "تنفيذ الاستدعاءات الخارجية على خدمة RADIUS.",
    "view_radius_status": "مراقبة المستخدمين والجلسات في خدمة RADIUS.",
    "disconnect_radius_user": "تنفيذ أمر فصل مستخدم متصل من RADIUS.",
    "manage_radius_settings": "تحديث إعدادات تكامل app_ad و RADIUS.",
    "view_notifications": "عرض مركز الإشعارات وآخر تحديثات الطلبات.",
    "manage_power_timer": "فتح صفحة عداد تحويل الكهرباء والتحكم بحالته.",
})

PERMISSION_GROUPS = [
    {
        "key": "beneficiaries",
        "title": "المستفيدون",
        "icon": "fa-users-viewfinder",
        "description": "بيانات المستفيدين الأساسية والاستيراد والتصدير.",
        "permissions": ["view", "add", "edit", "delete", "import", "export"],
    },
    {
        "key": "portal",
        "title": "حسابات البوابة والإنترنت",
        "icon": "fa-id-card-clip",
        "description": "حسابات دخول المشتركين وحسابات الإنترنت الدائمة.",
        "permissions": [
            "view_portal_accounts",
            "manage_portal_accounts",
            "view_user_accounts",
            "manage_user_accounts",
        ],
    },
    {
        "key": "cards",
        "title": "البطاقات والحصص",
        "icon": "fa-ticket",
        "description": "المخزون، الفئات، السياسات، المجموعات، وتسليم البطاقات.",
        "permissions": [
            "view_cards",
            "manage_card_inventory",
            "import_cards",
            "manage_card_categories",
            "manage_card_policies",
            "manage_quota_groups",
            "manage_card_requests",
            "usage_counter",
            "reset_weekly_usage",
        ],
    },
    {
        "key": "requests",
        "title": "طلبات الإنترنت",
        "icon": "fa-inbox",
        "description": "متابعة طلبات المشتركين واعتمادها وتنفيذ إجراءات RADIUS.",
        "permissions": [
            "view_internet_requests",
            "submit_internet_requests",
            "manage_internet_requests",
            "approve_internet_requests",
            "execute_radius_actions",
        ],
    },
    {
        "key": "radius",
        "title": "RADIUS و API",
        "icon": "fa-satellite-dish",
        "description": "فحص الربط، الجلسات النشطة، الإعدادات، وفصل المستخدمين.",
        "permissions": [
            "view_radius_status",
            "disconnect_radius_user",
            "manage_radius_settings",
        ],
    },
    {
        "key": "logs",
        "title": "السجلات والأرشيف",
        "icon": "fa-folder-tree",
        "description": "سجل العمليات، أرشيف البطاقات، النسخ الاحتياطي، والتصدير.",
        "permissions": [
            "view_audit_log",
            "view_archive",
            "archive_logs",
            "restore_archive",
            "export_archive",
            "delete_archive",
            "backup",
        ],
    },
    {
        "key": "system",
        "title": "النظام والإدارة",
        "icon": "fa-screwdriver-wrench",
        "description": "المستخدمون والصلاحيات، الإشعارات، التنظيف، والعداد.",
        "permissions": [
            "manage_accounts",
            "view_notifications",
            "manage_power_timer",
            "manage_bulk_ops",
            "manage_system_cleanup",
        ],
    },
]

TAWJIHI_YEARS = ["2006", "2007", "2008", "2009", "2010", "2011"]
TAWJIHI_BRANCHES = ["علمي", "أدبي", "شرعي", "زراعي", "صناعي", "تجاري", "فندقي"]
FREELANCER_SCHEDULE_OPTIONS = ["دوام كامل", "أحد ثلاثاء خميس", "سبت اثنين أربعاء", "بطاقة حسب الحاجة"]
TIME_MODE_OPTIONS = ["عشوائي", "وقت محدد"]
UNIVERSITIES_GAZA = ["الجامعة الإسلامية", "جامعة الأزهر", "جامعة الأقصى", "جامعة فلسطين", "جامعة القدس المفتوحة", "الكلية الجامعية للعلوم التطبيقية", "كلية العلوم والتكنولوجيا", "أخرى"]
UNIVERSITY_DAYS_OPTIONS = ["عشوائي", "سبت اثنين أربعاء", "أحد ثلاثاء خميس"]
INTERNET_ACCESS_METHOD_OPTIONS = ["يمتلك اسم مستخدم", "نظام البطاقات"]

USAGE_REASON_OPTIONS = ["تنفيذ تجربة", "تقديم اختبار", "حل واجب", "دراسة", "عمل حر", "تحميل محاضرات", "أخرى"]
CARD_TYPE_OPTIONS = ["ساعة", "ساعتين", "3 ساعات"]

CSV_IMPORT_COLUMNS = [
    "user_type",
    "first_name",
    "second_name",
    "third_name",
    "fourth_name",
    "phone",
    "notes",
    "tawjihi_year",
    "tawjihi_branch",
    "freelancer_specialization",
    "freelancer_company",
    "freelancer_schedule_type",
    "freelancer_internet_method",
    "freelancer_time_mode",
    "freelancer_time_from",
    "freelancer_time_to",
    "university_name",
    "university_number",
    "university_college",
    "university_specialization",
    "university_days",
    "university_internet_method",
    "university_time_mode",
    "university_time_from",
    "university_time_to",
]
